### ISSUE TITLE
Not an issue, just a message

### ISSUE THREAD

**Issue by cienciascontic** [NetTango/NetTango#4]
I want to thank you for this excelent project. I'm a NetLogo user and I'm now very happy to have NetTango. In the past, I have translated FrogPong into Spanish, now, I created my own application with NetTango. It's a very simple one, about ecology, more specific on the struggle between two ficticious species: molvas and sertanas. Molvas are foreing while sertanas are native.
Here's the link in case you want to take a look:

[https://cienciascontic.github.io/NetTango/molvas-vs-sertanas/](https://cienciascontic.github.io/NetTango/molvas-vs-sertanas/)

Thanks again.

Cristián

**Comment by michael-horn** [comment]
Awesome, Cristián! Thanks so much for sharing. 

Best,
Mike

**Comment by LaCuneta** [comment]
Thank you for the message, Cristián.  We're planning to create a better way of sharing NetTango models among users, and once that's complete your model would be a great addition.
